# Generated by Django 4.2.6 on 2023-10-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('numeroTelefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpleado', models.CharField(max_length=100)),
                ('apellidoEmpleado', models.CharField(max_length=100)),
                ('numeroTelefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('horarioTrabajo', models.CharField(max_length=20)),
                ('estadoEmpleo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descanso', 'En Descanso')], default='activo', max_length=10)),
                ('numeroEmpleado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tipos_de_servicio/', verbose_name='Cover')),
                ('duracionEstimada', models.DurationField()),
                ('costoEstimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('ultimoIngreso', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numeroReserva', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaHora', models.DateTimeField()),
                ('direccionCliente', models.CharField(max_length=200)),
                ('estadoReserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.empleado')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.tiposervicio')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario_perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario'),
        ),
    ]
