# Generated by Django 4.2.6 on 2023-10-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('NumeroTelefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('NumeroTelefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=200)),
                ('HorarioTrabajo', models.CharField(max_length=100)),
                ('EstadoEmpleo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descanso', 'En Descanso')], max_length=10)),
                ('NumeroEmpleado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('CorreoElectronico', models.EmailField(max_length=254, unique=True)),
                ('Contrasena', models.CharField(max_length=128)),
                ('FotoPerfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('UltimoIngreso', models.DateTimeField(auto_now=True)),
                ('Rol', models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('ReservaID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHora', models.DateTimeField()),
                ('DireccionCliente', models.CharField(max_length=200)),
                ('TipoServicio', models.CharField(max_length=100)),
                ('DuracionEstimada', models.DurationField()),
                ('EstadoReserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('CostoEstimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('NumeroConfirmacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario'),
        ),
    ]
