# Generated by Django 4.2.6 on 2023-10-29 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('fotoCliente', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('correoCliente', models.EmailField(max_length=254, unique=True)),
                ('direccionCliente', models.CharField(max_length=200)),
                ('telefonoCliente', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpleado', models.CharField(max_length=100)),
                ('apellidoEmpleado', models.CharField(max_length=100)),
                ('fotoEmpleado', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('correoEmpleado', models.EmailField(max_length=254, unique=True)),
                ('telefonoEmpleado', models.CharField(max_length=15)),
                ('direccionEmpleado', models.CharField(max_length=200)),
                ('horarioTrabajo', models.CharField(max_length=20)),
                ('estadoEmpleo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descanso', 'En Descanso')], default='activo', max_length=10)),
                ('numeroEmpleado', models.CharField(max_length=20, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tipos_de_servicio/', verbose_name='Cover')),
                ('duracionEstimada', models.DurationField()),
                ('costoEstimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numeroReserva', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaHora', models.DateTimeField()),
                ('direccionCliente', models.CharField(max_length=200)),
                ('estadoReserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.empleado')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.tiposervicio')),
            ],
        ),
    ]
