# Generated by Django 4.2.6 on 2023-10-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estadoEmpleo',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descanso', 'En Descanso')], default='activo', max_length=10),
        ),
    ]
