# Generated by Django 4.2.6 on 2023-10-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tipos_de_servicio/', verbose_name='Imagen'),
        ),
    ]
