# Generated by Django 4.2.6 on 2023-10-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_empleado_estadoempleo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='numeroConfirmacion',
        ),
    ]
