# Generated by Django 4.2.6 on 2023-10-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_tiposervicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='descripcion',
            field=models.TextField(verbose_name='description'),
        ),
    ]
