# Generated by Django 4.2.6 on 2023-10-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_tiposervicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numeroReserva',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
