# Generated by Django 4.2.6 on 2023-10-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_reserva_numeroreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numeroReserva',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
