# Generated by Django 4.2.6 on 2023-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_cliente_created_cliente_updated_empleado_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estadoReserva',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
